esphome:
  name: esphome-euc
  friendly_name: ESPHome EUC Sensor
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# To be able to get logs from the device via serial and api.
logger:
  level: VERY_VERBOSE

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    password: !secret wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  # Set up a wifi access point using the device name above
  ap:

web_server:
  port: 80
  include_internal: false
  version: 3
  sorting_groups:
    - id: sorting_group_states
      name: "States"
      sorting_weight: 1
    - id: sorting_group_sensors
      name: "Sensors"
      sorting_weight: 2

esp32_improv:
  authorizer: none

improv_serial:

esp32_ble_tracker:
  on_ble_advertise:
    - then:
