esphome:
  name: esphome-ble-scan

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# To be able to get logs from the device via serial and api.
logger:
  # level: VERY_VERBOSE

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    password: !secret wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  # Set up a wifi access point using the device name above
  ap:

web_server:
  port: 80
  include_internal: false
  version: 3

esp32_ble_tracker:

text_sensor:
  - platform: ble_scanner
    name: "BLE Devices Scanner"